language: node_js
node_js:
  - '12'
cache:
  directories:
    - $HOME/.composer/cache
    - npm

before_install: true
install:
  true
before_script: true
script:
#  - ./node_modules/.bin/JsHint test
#  - ./node_modules/.bin/Retire
#  - ./node_modules/.bin/Twly
after_script: true
#deploy:
#  provider: heroku
#  api_key:
#    secure: "key_replace"
#  app: app-eval